### PR TITLE
fixed parse for tree of length 1

### LINKED ISSUE #33: merkle root doesn't parse for tree length of 1

### PR DESCRIPTION
**Pull request by paulhandy**
resolves #33

### CODE REVIEW

File: mam/src/lib.rs [hunk 1]
```diff
@@ -101,6 +101,9 @@
 #[macro_use]
 extern crate alloc;
 
+#[macro_use]
+extern crate std;
```
Comment (th0br0) [inline mam/src/lib.rs]: Remove

File: mam/src/mam.rs [hunk 2]
```diff
@@ -192,13 +192,22 @@ where
...
-        pos += l.1;
-        let sib_end = pos + l.0 as usize * HASH_LENGTH;
-        let siblings = &payload[pos..sib_end];
-        merkle::root(&hmac, siblings, index as usize, curl);
+        if l.0 == 0 {
+            curl.absorb(&hmac);
+        } else {
+            // get address lite
+            {
+                curl.absorb(&hmac);
```
Comment (th0br0) [inline mam/src/mam.rs]: Duplicate of above case, just do 
Hmac.clone if l.0 != 0?

File: mam/src/mam.rs [hunk 3]
```diff
@@ -217,6 +226,126 @@ mod tests {
...
+
+        merkle::slice(&root, &mut root_trits);
+        merkle::slice(&next_root, &mut next_root_trits);
+
+        let index = 0;
+        let branch = merkle::branch(&root, index);
+        let branch_size = merkle::len(&branch);
+        let siblings_length = branch_size * HASH_LENGTH;
+
+        println!("bs {}", branch_size);
```
Comment (th0br0) [inline mam/src/mam.rs]: Remove println

File: mam/src/mam.rs [hunk 4]
```diff
@@ -217,6 +226,126 @@ mod tests {
     use super::*;
     use curl_cpu::*;
     use alloc::Vec;
+
+    #[test]
+    fn ham_fail() {
```
Comment (th0br0) [inline mam/src/mam.rs]: Rename to mam_no_siblings or so?
